# generated by fastapi-codegen:
#   filename:  quotes.yaml
#   timestamp: 2022-05-09T18:51:03+00:00

from __future__ import annotations

from fastapi import FastAPI

# from .models import Quotes0GetResponse
from .controller import Controller

app = FastAPI(
    title='Quotes API',
    version='1.0',
)

# NOTE: following method has been modified
@app.get('/quotes/0')
def get_quotes_0():
    """
    Returns a random quote
    """
    quote = Controller.get_quote()
    return {
        'statusCode': 200, 
        'Content-Type': 'application/json',
        'body': {
            'quote': quote, 
        }
    }
