openapi: 3.0.0
info:
  title: Quotes API
  version: "1.0"
components: 
  schemas:
    Quote:
      required:
        - id
        - text
        - author
      properties:
        id:
          type: integer
        text:
          type: string
        author:
          type: string
        popularity:
          type: number
        category:
          type: string
        tags:
          type: array
          items: 
            $ref: "#/components/schemas/QuoteTag"
    QuoteTag:
      required:
        - id
        - tag
      properties:
        id:
          type: integer
        tag:
          type: string
paths:
  /quotes/{id}:
    get:
      summary: Returns a quote given its id; for a random quote use id=0
      parameters: 
        - in: path
          name: id
          schema: 
            type: integer
          required: true
          description: id of the quote to get      
      responses:
        200:
          description: A quote
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Quote"
        404: 
          description: Not Found
          content:
            "application/json":
              schema:
                type: string
  /quotes:
    get:
      summary: Returns a list of quotes that satisfy a search criteria
      parameters: 
        - in: query
          name: text
          schema: 
            type: string 
          required: false
          description: text that quote's text must contain
        - in: query
          name: author
          schema: 
            type: string
          required: false
          description: author of the quote to get
        - in: query
          name: category
          schema: 
            type: string
          required: false
          description: category of the quote to get  
        - in: query
          name: tag
          schema: 
            type: string
          required: false
          description: tag that quote must have
        - in: query
          name: popularity
          schema: 
            type: number
          required: false
          description: minimum popularity that quote must have     
      responses:
        200:
          description: A list of quotes
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/Quote"
        404: 
          description: Not Found
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/Quote"