openapi: 3.0.0
info:
  title: Quotes API
  version: "1.0"
components: 
  schemas:
    Quote:
      required:
        - id
        - text
        - author
      properties:
        id:
          type: integer
        text:
          type: string
        author:
          type: string
        popularity:
          type: number
        category:
          type: string
        tags:
          type: array
          items: 
            $ref: "#/components/schemas/QuoteTag"
    QuoteTag:
      required:
        - id
        - tag
      properties:
        id:
          type: integer
        tag:
          type: string
paths:
  /quotes/0:
    get:
      summary: Returns a random quote
      responses:
        200:
          description: A random quote
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Quote"