openapi: 3.0.0
info:
  title: Quotes API
  version: "1.0"
components: 
  schemas:
    # NOTE: following schema name has been changed to singular 
    Quote:
      required:
        - id
        - text
        - author
      properties:
        id:
          type: integer
        text:
          type: string
        author:
          type: string
        popularity:
          type: number
        category:
          type: string
        # NOTE: following property has been added
        tags: 
          type: array
          items: 
            $ref: "#/components/schemas/QuoteTag"
    # NOTE: following schema name has been changed to singular
    QuoteTag:
      required:
        - id
        - tag
      properties:
        id:
          type: integer
        tag:
          type: string
# NOTE: following path section has been added
paths:
  /quotes/0:
    get:
      summary: Returns a random quote
      responses:
        200:
          description: A random quote
          content:
            "application/json":
              schema:
                required:
                  - statusCode
                  - Content-Type
                  - body
                properties:
                  statusCode: 
                    type: integer
                  Content-type: 
                    type: string 
                  body: 
                    $ref: "#/components/schemas/Quote"