# generated by fastapi-codegen:
#   filename:  quotes.yaml
#   timestamp: 2022-04-27T21:51:23+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import Quotes0GetResponse

# NOTE: added imports
from .controller import Controller

app = FastAPI(
    version='1.0',
    title='Quotes API',
)


# NOTE: method implementation modified
@app.get('/quotes/0', response_model=Quotes0GetResponse)
def get_quotes_0() -> Quotes0GetResponse:
    """
    Returns a random quote
    """
    quote = Controller.get_quote()
    return {
        'statusCode': 200, 
        'Content-type': 'application/json', 
        'body': quote.toJSON()
    }
    
