# generated by fastapi-codegen:
#   filename:  ../quotes.yaml
#   timestamp: 2022-04-27T21:51:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Quote(BaseModel):
    id: int
    text: str
    author: str
    popularity: Optional[float] = None
    category: Optional[str] = None
    tags: Optional[List[str]] = None

    # NOTE: added method below
    def toJSON(self):
        return {
            'id': self.id, 
            'text': self.text, 
            'author': self.author, 
            'popularity': self.popularity, 
            'category': self.category, 
            'tags': self.tags
        }

class Quotes0GetResponse(BaseModel):
    statusCode: int
    Content_type: Optional[str] = Field(None, alias='Content-type')
    body: Quote
