openapi: 3.0.0
info:
  title: Quotes API
  version: "1.0"
components: 
  schemas:
    Quote:
      required:
        - id
        - text
        - author
      properties:
        id:
          type: integer
        text:
          type: string
        author:
          type: string
        popularity:
          type: number
        category:
          type: string
        tags:
          type: array
          items: 
            $ref: "#/components/schemas/QuoteTag"
    QuoteTag:
      required:
        - id
        - tag
      properties:
        id:
          type: integer
        tag:
          type: string
paths:
  /quotes/{id}:
    get:
      summary: Returns a quote given its id; for a random quote use id=0
      parameters: 
        - in: path
          name: id
          schema: 
            type: integer
          required: true
          description: id of the quote to get      
      responses:
        200:
          description: A quote
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Quote"
        404: 
          description: Not Found
          content:
            "application/json":
              schema:
                type: string