# generated by fastapi-codegen:
#   filename:  quotes.yaml
#   timestamp: 2022-04-24T20:47:49+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import Quote
from .controller import Controller

app = FastAPI(
    version='1.0',
    title='Quotes API',
)


@app.get('/quote', response_model=None)
def get_quote() -> None:
    """
    Returns a random quote
    """
    return Controller.get_quote()
