# generated by fastapi-codegen:
#   filename:  quotes.yaml
#   timestamp: 2022-05-20T23:18:09+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import Quote
from fastapi import Response
from .controller import Controller

app = FastAPI(
    title='Quotes API',
    version='1.0',
)

@app.get('/quotes/0')
def get_quotes_0(response: Response) -> Quote:
    """
    Returns a random quote
    """
    response.status_code = 200
    return Controller.get_quotes_0()
