# generated by fastapi-codegen:
#   filename:  quotes.yaml
#   timestamp: 2022-08-29T15:47:38+00:00

from __future__ import annotations

from typing import Union

from fastapi import FastAPI

from .models import Quote
from fastapi import Response
from sqlalchemy.sql import func
from sqlalchemy.orm import sessionmaker
from .db_helper import DBHelper

app = FastAPI(
    title='Quotes API',
    version='1.0',
)


@app.get('/quotes/{id}', response_model=dict)
def get_quotes_id(id: int, response: Response) -> Union[dict, str]:
    """
    Returns a quote given its id; for a random quote use id=0
    """
    engine = DBHelper.get_engine()
    Session = sessionmaker(engine)
    session = Session()
    result = session.query(Quote)
    quote = result.order_by(func.random()).first() if id == 0 else result.get(id)
    if quote:
        response.status_code = 200
        return quote.__dict__
    else:
        response.status_code = 404
        return {}

