# generated by fastapi-codegen:
#   filename:  quotes.yaml
#   timestamp: 2022-05-26T20:18:18+00:00

from __future__ import annotations

from typing import Union

from fastapi import FastAPI

from .models import Quote

from fastapi import Response
from .controller import Controller

app = FastAPI(
    title='Quotes API',
    version='1.0',
)


# @app.get('/quotes/{id}', response_model=Quote, responses={'404': {'model': str}})
# def get_quotes_id(id: int) -> Union[Quote, str]:
#     """
#     Returns a quote given its id; for a random quote use id=0
#     """
#     pass

@app.get('/quotes/{id}', response_model=dict)
def get_quotes_id(id: int, response: Response) -> Quote:
    """
    Returns a quote given its id; for a random quote use id=0
    """
    quote = Controller.get_quotes_id(id)
    print(quote)
    if quote:
        response.status_code = 200
        return quote.__dict__
    else:
        response.status_code = 404
        return {'message': 'Not Found!'}